INSERT INTO t_environments ("name", description) VALUES('cartaomontreal', 'Montreal');
INSERT INTO t_environments ("name", description) VALUES('milla', 'Milla');
INSERT INTO t_environments ("name", description) VALUES('frigelar', 'Frigelar');
INSERT INTO t_environments ("name", description) VALUES('facilprapagar', 'São Vicente');
INSERT INTO t_environments ("name", description) VALUES('cartaolopes', 'Cartão Lopes');
INSERT INTO t_environments ("name", description) VALUES('vuon', 'Vuon PL');
INSERT INTO t_environments ("name", description) VALUES('vuon-convenio', 'Vuon Convenio');
INSERT INTO t_environments ("name", description) VALUES('savegnagoprivate', 'Savegnago');
INSERT INTO t_environments ("name", description) VALUES('cartaolevemais', 'Pague Menos');
INSERT INTO t_environments ("name", description) VALUES('cartaoconfianca', 'DaVó');
INSERT INTO t_environments ("name", description) VALUES('sol', 'Sol (AKKI)');
INSERT INTO t_environments ("name", description) VALUES('flamcard', 'Flamboyan');
INSERT INTO t_environments ("name", description) VALUES('avenida', 'Avenida');
INSERT INTO t_environments ("name", description) VALUES('voxcred', 'Vox');
INSERT INTO t_environments ("name", description) VALUES('humanitarian', 'Humanitarian');
INSERT INTO t_environments ("name", description) VALUES('bahamascred', 'Bahamas');
INSERT INTO t_environments ("name", description) VALUES('avantisys', 'Caedu');
INSERT INTO t_environments ("name", description) VALUES('festclub', 'FestCard - Oscar Calçados');
INSERT INTO t_environments ("name", description) VALUES('cartaoemporioalex', 'Empório Alex');
INSERT INTO t_environments ("name", description) VALUES('cassol', 'Cassol');
INSERT INTO t_environments ("name", description) VALUES('Becker', 'Becker');
INSERT INTO t_environments ("name", description) VALUES('martminas', 'MartMinas');
INSERT INTO t_environments ("name", description) VALUES('credsea', 'Credsea South');
INSERT INTO t_environments ("name", description) VALUES('servirprivate', 'Bramil PL - Servir');
INSERT INTO t_environments ("name", description) VALUES('servirconvenio', 'Bramil Convenio - Servir');
INSERT INTO t_environments ("name", description) VALUES('clubdemais', 'DB - Clubdemais');
INSERT INTO t_environments ("name", description) VALUES('confpay', 'ConfPay - Confiança');
INSERT INTO t_environments ("name", description) VALUES('ngvcred', 'NGV');
INSERT INTO t_environments ("name", description) VALUES('drogal', 'Drogal');
INSERT INTO t_environments ("name", description) VALUES('cartaotimax', 'Timax');
INSERT INTO t_environments ("name", description) VALUES('torratorra', 'Torra');
INSERT INTO t_environments ("name", description) VALUES('taustepay', 'Tauste Pay');
INSERT INTO t_environments ("name", description) VALUES('nossopay', 'NossoPay - Super Nosso');