INSERT INTO t_environments (id, "name", description, active) VALUES(1, 'cartaomontreal', 'Montreal', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(2, 'milla', 'Milla', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(3, 'frigelar', 'Frigelar', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(4, 'facilprapagar', 'São Vicente', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(5, 'cartaolopes', 'Cartão Lopes', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(6, 'vuon', 'Vuon PL', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(7, 'vuon-convenio', 'Vuon Convenio', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(8, 'savegnagoprivate', 'Savegnago', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(9, 'cartaolevemais', 'Pague Menos', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(10, 'cartaoconfianca', 'DaVó', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(11, 'sol', 'Sol (AKKI)', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(12, 'flamcard', 'Flamboyan', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(13, 'avenida', 'Avenida', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(14, 'voxcred', 'Vox', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(15, 'humanitarian', 'Humanitarian', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(16, 'bahamascred', 'Bahamas', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(17, 'avantisys', 'Caedu', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(18, 'festclub', 'FestCard - Oscar Calçados', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(19, 'cartaoemporioalex', 'Empório Alex', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(20, 'cassol', 'Cassol', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(21, 'Becker', 'Becker', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(22, 'martminas', 'MartMinas', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(23, 'credsea', 'Credsea South', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(24, 'servirprivate', 'Bramil PL - Servir', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(25, 'servirconvenio', 'Bramil Convenio - Servir', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(26, 'clubdemais', 'DB - Clubdemais', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(27, 'confpay', 'ConfPay - Confiança', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(28, 'ngvcred', 'NGV', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(29, 'drogal', 'Drogal', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(30, 'cartaotimax', 'Timax', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(31, 'torratorra', 'Torra', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(32, 'taustepay', 'Tauste Pay', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(33, 'nossopay', 'NossoPay - Super Nosso', true);
INSERT INTO t_environments (id, "name", description, active) VALUES(34, 'conveniomartminas', 'MartMinas Convenio', true);
